### ISSUE TITLE
Find_by with { id: nil } showing all subscriptions 

### ISSUE THREAD

**Issue by fernandomcunha** [pagarme/pagarme-ruby#64]
Hello,

I know that's not the best practice but if you call `PagarMe::Subscription.find_by(id: nil)`, it return all the subscriptions and I got this scenario on the system that I work for.

Regards,

**Comment by leonardo-barbosa** [comment]
Hi @fernandomcunha , how you doing?

Thanks for the info!

Actually the `find_by` method works just like if you we're querying directly into the API, even accepting a `Hash` as one of its params, and as result of it, if you just pass a `nil` ID it will search for the top 10 last transactions (unless you send the `count:` param on the request, because then it will show the number passed).

For a search by the ID, we would recomend you to use the `find_by_id` method, that doesn't allow `nil` values.

Does it make sense? :D

If you have any doubts, i'm here to help.

Regards,

**Comment by fernandomcunha** [comment]
Hi @leonardo-barbosa I'm fine, thanks.

**Comment by leonardo-barbosa** [comment]
Hi @fernandomcunha .

Yes, it's exactly like you said!

The `find` method is a alias of the method `find_by_id`, i.e., both of them will give the same result.

Let me know, if you need help in anything else. =)

Regards,

**Comment by fernandomcunha** [comment]
I am closing the issue as my question has been answered.

Thanks @leonardo-barbosa 

Regards
